import type { Metadata } from "next";
import Nav from './components/nav'
import { Poppins } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"


import "./globals.css";



const poppins = Poppins({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Common Grounds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <body className={poppins.className}>
        <main>
          <Nav />
          {children}
          <Analytics />

        </main>
      </body>
    </html>
  );
}

