import type { Metadata } from "next";
import Nav from './components/nav'

import "./globals.css";



export const metadata: Metadata = {
  title: "Common Grounds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <body className={`antialiased `}>
        
          <Nav />
          {children}
        
      </body>
    </html>
  );
}

